### ISSUE TITLE
How to register events, registerOutgoingPluginChannel

### ISSUE THREAD

**Issue by maxim19116** [netherrack/netherrack#13]
Help how to register events? And when this do?

plugin.getServer().getMessenger().registerOutgoingPluginChannel((Plugin) this, "BungeeCord");
Bukkit.getMessenger().registerOutgoingPluginChannel((Plugin) Main.plugin, strOut);

**Comment by mhsjlw** [comment]
This is a now-defunct pet project, I recommend you use a server like Glowstone if you're looking for a Bukkit/Spigot alternative. We do not actually fully support the Bukkit API. Sorry.

**Comment by maxim19116** [comment]
This very good project! I use GlowStone, but his not satisfied me

Help me plz:)
